# Generated by Django 3.2.12 on 2023-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theverge', '0003_auto_20230328_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
